services:
  ros_gazebo:
    build: .
    container_name: jazzy_harmonic_sim
    platform: linux/arm64 # <-- FORCE APPLE SILICON NATIVE
    privileged: true
    network_mode: bridge
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:0
      - LIBGL_ALWAYS_SOFTWARE=1
      - GALLIUM_DRIVER=llvmpipe
    volumes:
      - ./src:/root/ros2_ws/src