controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    r6bot_controller:
      type: ros2_control_demo_example_7/RobotController

    # Register the gripper controller
    gripper_controller:
      type: forward_command_controller/ForwardCommandController


r6bot_controller:
  ros__parameters:
    type: ros2_control_demo_example_7/RobotController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

# Gripper controller parameters
gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_joint
      - gripper_right_joint
    interface_name: position